version: '3.8'

services:
  keycloak-sample:
    image: quay.io/keycloak/keycloak:20.0.3
    container_name: keycloak-sample
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: "true"
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_USER: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
#      KEYCLOAK_DATABASE_NAME: "keycloak"
#      KEYCLOAK_DATABASE_USER: "keycloak"
#      KEYCLOAK_DATABASE_PASSWORD: "keycloak"
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      DB_SCHEMA: public
#      KEYCLOAK_HTTP_PORT: "8080"
    command:
      - start-dev
    ports:
      - "8081:8080"
      - "8787:8787"
    depends_on:
      - keycloak-sample-db
  keycloak-sample-db:
    image: postgres:alpine
    container_name: keycloak-sample-db
    environment:
      POSTGRES_USER: "keycloak"
      POSTGRES_PASSWORD: "keycloak"
      POSTGRES_DB: "keycloak"
    volumes:
      - ./db/keycloak/:/var/lib/postgresql/data/
  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DRIVER: pgsql
      ADMINER_DEFAULT_SERVER: business-db
      ADMINER_PLUGINS: tables-filter tinymce
      ADMINER_DESIGN: nette
    expose:
      - "8082"
    restart: always
