openapi: 3.0.3
info:
  title: sample-api
  version: v0.1
tags:
  - name: sample-api
paths:
  /samples/called-by-webclient:
    get:
      tags:
        - sample-controller
      operationId: calledByWebclient
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'sample-api-schema.yaml#/components/schemas/sample'
        '204':
          description: 'No Content'
  /samples/hello-world:
    get:
      tags:
        - sample-controller
      operationId: helloWorld
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
